// Centrale NL-strings voor /spelen. Toon: direct, feit-taal, geen hype.
// Zie docs/tone-of-voice-alvah-site-nl.md — één niveau warmer dan dossier,
// maar zonder "kanjer/held/ons mannetje"-stem.

export const NL = {
  // Algemeen
  start: 'Start',
  pauze: 'Pauze',
  doorgaan: 'Doorgaan',
  stop: 'Stop',
  klaar: 'Klaar',
  volgende: 'Volgende',
  opnieuw: 'Nog een keer',
  teMoeilijk: 'Dit is te moeilijk',
  nietTeMoeilijk: 'Laat maar',
  uitleg: 'Uitleg',
  voorbeeld: 'Voorbeeld',
  luisteren: 'Voorlezen',
  geluidAan: 'Geluid aan',
  geluidUit: 'Geluid uit',

  // Feedback (geen uitroeptekens, feit-taal)
  goedBezig: 'Goed bezig',
  probeerMaar: 'Probeer maar',
  nogEenKeer: 'Nog een keer',
  jeHadXvanY: (x, y) => `Je had ${x} van de ${y} goed`,
  jouwHoogsteRij: (n) => `Jouw hoogste rij was ${n}`,
  ditIsJeNiveau: (n) => `Dit niveau beheers je nu: ${n}`,

  // Landing
  spelen: {
    titel: 'Spelen',
    lede: 'Kies een spel, of speel het spel dat vandaag wordt aangeraden.',
    vandaag: 'Vandaag',
    andere: 'Andere spellen',
    nogNietBeschikbaar: 'Nog niet beschikbaar',
    binnenkort: 'Binnenkort',
  },

  // Spel-titels en korte beschrijvingen
  spel: {
    simon: {
      titel: 'Simon',
      kort: 'Onthoud de volgorde van kleuren en klanken.',
      uitleg: 'Kijk en luister goed naar de kleuren. Tik ze daarna in dezelfde volgorde aan.',
      kijkGoed: 'Kijk goed',
      jouwBeurt: 'Jouw beurt',
      goed: 'Juist',
      ietsKorter: 'Oké, iets korter',
      hoogsteRij: 'Hoogste rij',
      eindeCap: 'Je hebt de hoogste rij gehaald',
    },
    zoeken: {
      titel: 'Zoeken',
      kort: 'Zoek de rode kikker tussen de groene.',
      uitleg: 'Tik de rode kikker zo snel als je kunt. Let op: de andere kikkers zijn groen.',
      jouwBeurt: 'Zoek de rode',
      goed: 'Gevonden',
      fout: 'Dat was een groene',
      setSize: 'Aantal kikkers',
    },
    corsi: {
      titel: 'Corsi',
      kort: 'Onthoud welke sterren oplichtten en in welke volgorde.',
      uitleg: 'Kijk goed welke sterren oplichten. Tik ze daarna aan in dezelfde volgorde.',
      kijkGoed: 'Kijk goed',
      jouwBeurt: 'Jouw beurt',
      goed: 'Juist',
      ietsKorter: 'Oké, iets korter',
      hoogsteRij: 'Langste rij',
      eindeCap: 'Je hebt de hoogste rij gehaald',
    },
    'day-night': {
      titel: 'Dag & Nacht',
      kort: 'Zeg het omgekeerde van wat je ziet.',
      uitleg: 'Zie je de zon? Tik dan op NACHT. Zie je de maan? Tik dan op DAG.',
      klaarVoor: 'Klaar?',
      dag: 'Dag',
      nacht: 'Nacht',
      goed: 'Juist',
      bijnaGoed: 'Andersom',
      rondeVan: (i, n) => `Ronde ${i} van ${n}`,
    },
    wisselen: {
      titel: 'Wisselen',
      kort: 'Soms kijk je naar de kleur, soms naar de vorm.',
      uitleg: 'Lees eerst de hint. "Kleur" betekent: kijk naar de kleur. "Vorm" betekent: kijk naar de vorm. Tik dan links of rechts.',
      cueKleur: 'Kleur',
      cueVorm: 'Vorm',
      instructieKleur: 'Rood links, blauw rechts',
      instructieVorm: 'Vierkant links, cirkel rechts',
      links: 'Links',
      rechts: 'Rechts',
      blokTitel: {
        'pure-kleur': 'Alleen kleur',
        'pure-vorm': 'Alleen vorm',
        'switch': 'Afwisselen',
      },
      blokUitleg: {
        'pure-kleur': 'Let alleen op de kleur.',
        'pure-vorm': 'Let alleen op de vorm.',
        'switch': 'De hint wisselt. Lees hem elke keer.',
      },
      goed: 'Juist',
      fout: 'Andersom',
      switchCost: 'Wisselkost',
    },
  },

  // Admin-pagina
  admin: {
    titel: 'Admin',
    lede: 'Overzicht van alle sessies. Niets verlaat deze browser.',
    dezeWeek: 'Deze week',
    minutenGespeeld: 'Minuten gespeeld',
    sessiesTotaal: 'Sessies totaal',
    laatsteSessies: 'Laatste sessies',
    geenData: 'Nog geen sessies gespeeld.',
    kopieer: 'Kopieer JSON',
    kopieerd: 'Gekopieerd',
    download: 'Download JSON',
    importeer: 'Importeer JSON',
    importeerd: 'Geïmporteerd',
    importFout: 'Ongeldige JSON',
    wisAlles: 'Wis alles',
    wisBevestig: 'Zeker weten? Alle sessies worden gewist.',
    wisGedaan: 'Gewist',
    datum: 'Datum',
    niveau: 'Niveau',
    duur: 'Duur',
    accuracy: 'Accuracy',
    meanRT: 'Gem. RT',
  },

  // Navigatie
  terug: 'Terug',
  terugNaarSpelen: 'Terug naar spelen',
  jouwReis: 'Jouw reis',
};
